<?php

namespace Zelazowy\Bundle\MemcachedBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getActive($active = 1)
    {
        return $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.active = :active')
                ->setParameter('active', $active)
                ->orderBy('u.name', 'asc')
                ->getQuery()
                ->getResult();
    }
}
